### ISSUE TITLE
不明白什么是”暂存区"，无法顺利发布内容

### ISSUE THREAD

**Issue by raining1123** [Zeng1998/memos-utools#1]
![image](https://user-images.githubusercontent.com/17892238/210161754-fe457d78-3ab4-4d3d-9441-8ad40eaa5947.png)

**Comment by Zeng1998** [comment]
暂存区就是说我们可以多次添加一些内容，再一起发布。

图上的错误似乎是memos新版存在的问题，通过api发布都会报这个错。具体问题我们再去看一下。

**Comment by Zeng1998** [comment]
Memos相应问题已解决：https://github.com/usememos/memos/pull/885

可以等Memos新版本发布或者更新最新的开发版本即可。

**Comment by raining1123** [comment]
好的，非常感谢！
